### ISSUE TITLE
CircleCI: Builds fail due to frequent `ContextualVersionConflict` errors

### ISSUE THREAD

**Issue by co-robo** [coala/coala-quickstart#183]
Opened by @satwikkansal at [gitter/coala/coala](https://gitter.im/coala/coala?at=59df654cbbbf9f1a385121a5)

**Comment by satwikkansal** [comment]
https://circleci.com/gh/coala/coala-quickstart/366

**Comment by satwikkansal** [comment]
```
pkg_resources.ContextualVersionConflict: (setuptools 12.0.5 (/home/ubuntu/.pyenv/versions/3.4.3/lib/python3.4/site-packages), Requirement.parse('setuptools>=17.0'), {'coala'})

../../../../.pyenv/versions/3.4.3/lib/python3.4/site-packages/pkg_resources/__init__.py:810: C
```

**Comment by rpanczer** [comment]
@satwikkansal Mind if I take care of this one?

**Comment by satwikkansal** [comment]
Hey @rpanczer, sure ;)

**Comment by RaiVaibhav** [comment]
@satwikkansal  Cirlce CI failing with [error log](https://circleci.com/gh/RaiVaibhav/coala-quickstart/4)
I think this is because of [issue](https://github.com/coala/coala/issues/4794) solved the conflict version problem but it created a new [issue](https://circleci.com/gh/RaiVaibhav/coala-quickstart/4)

**Comment by RaiVaibhav** [comment]
And error is same as defined in [issue](https://github.com/coala/coala/issues/4794)

**Comment by jayvdb** [comment]
I've fixed this as part of https://github.com/coala/coala-quickstart/pull/193
