### ISSUE TITLE
Create sections using .editorconfig if present

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-quickstart#79]
http://editorconfig.org/

**Comment by jack17529** [comment]
@jayvdb can you please explain the issue?

**Comment by satwikkansal** [comment]
@jayvdb I've created a custom `.editorconfig` parser which is able to extract the properties and values. Just wanted to consult you for the next steps :)
Taking a look at the [EditorConfig properties](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties) wiki, I realized that there is mismatch in the "names of the properties in the EditorConfig files" and the "names of settings of bears that can utilize that property". Example, in ".editorconfig", to define a preferred quotation style, we write `quote_type = single` but for the QuotesBear, we write `preferred_quotation = '` in the ".coafile".

**One possible approach is:**
We can first define a meta dictionary like 
```py
editorconfig_meta = {
	"property_name": [list, of, bears, affected, by, the, property]
}
```
and because every bear may use this setting differently, we'd have to write mapping logic to map the "property and its value" to the "bear's setting and its value". Example, the values of the property `max_line_length` in .editorconfig can either be a positive integer or just the string "off". So the mapping logic corresponding to the `max_line_length` property will have to take care of "off" values because our LineLengthBear doesn't understand what "off" means.

The problem with this approach is we will have to write a lot of mapping functions corresponding to combinations of "every property in .editorconfig and every bear that can utilize that property" and we'll have to maintain them indefinitely. One idea to reduce the mapping maybe to follow the ".editorconfig" like property styles in our bears' settings as well (like replacing `preferred_quotation` with `quote_type` in QuoteBear and every other bear with similar setting).

**Comment by jayvdb** [comment]
> because every bear may use this setting differently

That may be the case now, but ... we are standardising the names of settings, irrespective of the bears.
i.e. the bears must use the same name for the same concept, and we are fixing discrepancies where they exist.
So, use the most common setting only, and create bugs for any discrepancy that you notice.

**Comment by jayvdb** [comment]
Also, please analyse https://github.com/editorconfig/editorconfig-core-py , to see if it is not usable instead of a custom parser? (and custom writer for https://github.com/coala/coala/issues/4098)

**Comment by satwikkansal** [comment]
I did analyze https://github.com/editorconfig/editorconfig-core-py , actually the way it works is not suitable for this issue. 
It has only `get_properties` method as the interface which takes in filename/file globs as argument and returns the configurations of the sections in ".editorconfig" that match the argument passed.
However, I think the behavior we want is to extract the all the sections and corresponding configurations from the ".editorconfig". My [implementation](https://github.com/satwikkansal/coala-quickstart/blob/79/coala_quickstart/parsers/editorconfig_parser.py) of the custom parser is derived from editorconfig-core-py's [parser](https://github.com/editorconfig/editorconfig-core-py/blob/master/editorconfig/ini.py) adapted according to our use case.

**Comment by jayvdb** [comment]
I suggest talking with that project, asking them if they are interested in more methods being added, to achieve what you need.  Then everyone benefits; most of all, coala benefits in having someone else maintaining the functionality we rely on.

**Comment by Makman2** [comment]
Imo this one is not `difficulty/low`, at least `difficulty/medium`.

**Comment by satwikkansal** [comment]
Done with https://github.com/coala/coala-quickstart/pull/133/commits/54629969935a522f8dadcafee2443d02e2ac420f
